# Generated by Django 4.2 on 2023-05-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roomName',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
