# Generated by Django 4.2 on 2023-05-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_profile_roomname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='razorpay_signature',
        ),
    ]
