# Generated by Django 4.2 on 2023-05-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0004_remove_profile_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
