# Generated by Django 4.2 on 2023-05-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0006_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
